name: CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compilation_tests:
    continue-on-error: true 
    strategy:
      matrix:
        os: [ubuntu18.04, centos7, fedora32_mingw]
        build: [cmake_kokkos_mpi_openmp_clang_shared]
    runs-on: "lammps/buildenv:${{ matrix.os }}"
    env:
      CCACHE_HASH: ccache-${{ matrix.os }}-${{ matrix.build }}
      LAMMPS_COMPILE_NPROC: 2
      LAMMPS_CI_RUNNER: github
      CCACHE_DIR: ~/.ccache
    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%s)"
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ env.CCACHE_HASH }}-${{ steps.time.outputs.time }}
          restore-keys: ${{ env.CCACHE_HASH }}
      - uses: actions/checkout@master
      - name: Install Deps
        run: |
          git clone --depth 1 https://github.com/lammps/lammps-testing.git
      - name: Build
        run: |
          ccache -z
          export LAMMPS_DIR=$PWD
          lammps_testing/scripts/builds/${{ matrix.build }}.sh
          ccache -s
      - name: Tests
        run: cd build && ctest --output-on-failure
      - name: Install
        run: cmake --install build
