name: CI
on: 
  push:
    branches:
      - master
      - github-actions-wip 
  pull_request:
    branches:
      - master

jobs:
  CI:
    continue-on-error: true 
    strategy:
      matrix:
        distro: ["ubuntu18.04", "centos7"]
        set: ["all_off", "most", "minimal", "nolib", "kokkos-serial", "kokkos-openmp"]
        cxx: ["g++", "clang++"]
        cmake_build_type: ["Release", "Debug"]
    runs-on: ubuntu-latest
    container: lammps/buildenv:${{ matrix.distro }}
    env:
      CCACHE_HASH: ccache-${{ matrix.distro}}-${{ matrix.set }}-${{ matrix.cxx }}-${{ matrix.cmake_build_type }}
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=time::$(date +%s)"
          if ${{ matrix.cxx == 'clang++' }}; then echo "::set-output name=cc::clang"; else echo "::set-output name=cc::gcc"; fi
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ env.CCACHE_HASH }}-${{ steps.setup.outputs.time }}
          restore-keys: ${{ env.CCACHE_HASH }}
      - uses: actions/checkout@master
      - name: CMake
        run: cmake -B builddir -C cmake/presets/${{ matrix.set }}.cmake -DENABLE_TESTING=ON
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCMAKE_C_COMPILER=${{ steps.setup.outputs.cc }}
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} 
          cmake
      - name: Build
        run: |
          ccache -z
          cmake --build builddir --parallel 3 
          ccache -s
      - name: Tests
        run: cd builddir && ctest --output-on-failure
      - name: Install
        run: cmake --install builddir
